### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mcccoleman** [learn-co-curriculum/careers-building-an-in-person-network#1]
sentence reads "Meetup iis a platform where anyone can organize an in-person get together around a certain topic."

**Comment by mcccoleman** [comment]
Sorry, found another one. Text is "Meeting people at volunteer events shows the people present that you’re passionate about programming and you work hard.Example: Girls Who Code"

**Comment by rrcobb** [comment]
Thanks for reporting! Fixed these ones.
